package models

//
//var ActivitiesEN = []string{
//	"Go for a walk",
//	"Read a book",
//	"Watch a movie",
//	"Cook a new recipe",
//	"Exercise at home",
//	"Learn a new language",
//	"Write a journal",
//	"Meditate",
//	"Do yoga",
//	"Play a board game",
//	"Try painting or drawing",
//	"Listen to a podcast",
//	"Organize your room",
//	"Learn to play a musical instrument",
//	"Take photos outdoors",
//	"Go cycling",
//	"Watch a documentary",
//	"Plan your next vacation",
//	"Try gardening",
//	"Write a short story",
//	"Do a puzzle",
//	"Learn coding",
//	"Explore a new hobby",
//	"Clean up your computer files",
//	"Learn origami",
//	"Volunteer online",
//	"Try knitting or sewing",
//	"Call a friend or family member",
//	"Research an interesting topic",
//	"Do a home workout",
//	"Make a vision board",
//	"Try baking",
//	"Go for a run",
//	"Create a playlist",
//	"Do some stretching",
//	"Watch a stand-up comedy",
//	"Experiment with photography",
//	"Try a new hairstyle",
//	"Play a video game",
//	"Build something with LEGO",
//	"Go bird watching",
//	"Learn to dance",
//	"Plan a surprise for someone",
//	"Write a letter to your future self",
//	"Try a new sport",
//	"Visit a museum or gallery online",
//	"Make a time capsule",
//	"Do some DIY home decor",
//	"Practice calligraphy",
//	"Create digital art",
//	"Learn about astronomy",
//	"Play a musical quiz",
//	"Start a blog",
//	"Create a budget plan",
//	"Learn about history",
//	"Explore local nature",
//	"Do a random act of kindness",
//	"Clutter your wardrobe",
//	"Learn to juggle",
//	"Test a new app or tool",
//	"Make a list of goals",
//	"Watch a sunset or sunrise",
//	"Build a birdhouse",
//	"Try speed reading",
//	"Learn basic first aid",
//	"Make homemade gifts",
//	"Do a crossword puzzle",
//	"Host a movie night",
//	"Learn to make cocktails or mocktails",
//	"Start a scrapbook",
//	"Do a photography challenge",
//	"Plant a tree",
//	"Explore a new genre of music",
//	"Write a poem",
//	"Take an online class",
//	"Do a science experiment at home",
//	"Create a podcast",
//	"Play with your pet",
//	"Learn about your ancestry",
//	"Try a new workout routine",
//	"Experiment with makeup",
//	"Watch a sports game",
//	"Take a nap",
//	"Plan a picnic",
//	"Try geocaching",
//	"Do a tech detox",
//	"Learn about minimalism",
//	"Create a stop-motion video",
//	"Learn basic coding skills",
//	"Explore local history",
//	"Write a book or movie review",
//	"Try a new kind of tea or coffee",
//	"Sketch or doodle",
//	"Make a list of things you're grateful for",
//	"Build a paper airplane",
//	"Try learning sign language",
//	"Explore maps of new places",
//	"Write a letter to a friend",
//	"Learn to whistle",
//	"Create a mini photo album",
//	"Build a house of cards",
//	"Try a relaxation technique",
//}

var ActivitiesRU = []string{
	"Прогуляться на улице",
	"Почитать книгу",
	"Посмотреть фильм",
	"Приготовить новое блюдо",
	"Позаниматься дома спортом",
	"Выучить новый язык",
	"Вести дневник",
	"Медитировать",
	"Заняться йогой",
	"Поиграть в настольную игру",
	"Попробовать рисовать или раскрашивать",
	"Послушать подкаст",
	"Убраться в комнате",
	"Научиться играть на музыкальном инструменте",
	"Сделать фотографии на улице",
	"Покататься на велосипеде",
	"Посмотреть документальный фильм",
	"Спланировать следующий отпуск",
	"Попробовать заняться садоводством",
	"Написать короткий рассказ",
	"Собрать пазл",
	"Изучать программирование",
	"Освоить новое хобби",
	"Очистить файлы на компьютере",
	"Научиться делать оригами",
	"Помочь волонтёрам онлайн",
	"Попробовать вязание или шитье",
	"Позвонить другу или родственнику",
	"Изучить интересную тему",
	"Сделать домашнюю тренировку",
	"Создать доску визуализации",
	"Испечь что-то новое",
	"Пойти на пробежку",
	"Составить новый плейлист",
	"Сделать растяжку",
	"Посмотреть комедийное шоу",
	"Провести эксперимент с фотографией",
	"Попробовать новую прическу",
	"Поиграть в видеоигру",
	"Построить что-то из LEGO",
	"Походить по парку и понаблюдать за птицами",
	"Научиться танцевать",
	"Спланировать сюрприз для кого-то",
	"Написать письмо самому себе в будущее",
	"Попробовать новый вид спорта",
	"Посетить музей или галерею онлайн",
	"Сделать капсулу времени",
	"Заняться DIY-декором дома",
	"Практиковать каллиграфию",
	"Создать цифровое искусство",
	"Изучить основы астрономии",
	"Сыграть в музыкальную викторину",
	"Начать вести блог",
	"Составить бюджет",
	"Изучить историю",
	"Прогуляться на природе",
	"Совершить случайный добрый поступок",
	"Разобрать гардероб",
	"Научиться жонглировать",
	"Протестировать новое приложение",
	"Составить список целей",
	"Посмотреть закат или рассвет",
	"Построить скворечник",
	"Освоить скорочтение",
	"Выучить основы первой помощи",
	"Сделать подарки своими руками",
	"Решить кроссворд",
	"Устроить вечер кино",
	"Научиться делать коктейли или напитки",
	"Создать скрап бук",
	"Провести фото челлендж",
	"Посадить дерево",
	"Изучить новый музыкальный жанр",
	"Написать стихотворение",
	"Пройти онлайн-курс",
	"Сделать научный эксперимент дома",
	"Создать подкаст",
	"Поиграть с питомцем",
	"Узнать о своей родословной",
	"Попробовать новый комплекс упражнений",
	"Экспериментировать с макияжем",
	"Посмотреть спортивный матч",
	"Вздремнуть",
	"Спланировать пикник",
	"Попробовать геокешинг",
	"Сделать цифровой детокс",
	"Узнать больше о минимализме",
	"Создать видео-стопорен",
	"Изучить основы программирования",
	"Узнать больше о местной истории",
	"Написать рецензию на фильм или книгу",
	"Попробовать новый сорт чая или кофе",
	"Набросать что-то в блокноте",
	"Составить список того, за что вы благодарны",
	"Сделать бумажный самолетик",
	"Начать учить язык жестов",
	"Изучить карты новых мест",
	"Написать письмо другу",
	"Научиться свистеть",
	"Создать мини-альбом фотографий",
	"Построить карточный домик",
	"Попробовать технику релаксации",
}
